### ISSUE TITLE
Unable to display rspec json reports

### ISSUE THREAD

**Issue by srvadlam** [web-innovate/bootstraped-multi-test-results-report#36]
I have trying to use you plugin to display rpsec json report. The report is on slave which would be copied to master. However, when I click on the link for the report get 404 error below. Additionally, the plugin would not create directory structure required on the jenkins master
```
<jenkins_url>/<project_name>/rspec-reports-with-handlebars/. Reason:

    Not Found


[RSpecReportPublisher] Compiling RSpec Html Reports ...
[RSpec test report builder] Copying all xml files from slave: 
/spec/reports to master reports directory: 
/builds/15/rspec-reports-with-handlebars
[RSpec test report builder] xml path for the reports might be wrong, 
```

**Comment by BogdanLivadariu** [comment]
@srvadlam  what is the target value set for the reports ?

**Comment by BogdanLivadariu** [comment]
ping @srvadlam

**Comment by srvadlam** [comment]
@BogdanLivadariu we have abandoned this plugin and moved on to use JUnitResultArchiver, which seems to work for now.

**Comment by mareiou** [comment]
I am seeing the same error. I think the problem is how the path is configured...
In my case is looking for $jenkins_home/job/$name_of_workspace/$job_number/rspec-reports-with-handlebars/.
I think it should look for $jenkins_home/jobs/$name_of_workspace/builds/$job_number/rspec-reports-with-handlebars/xmlData
